### PR TITLE
Argcomplete

### PR DESCRIPTION
**Pull request by sedrubal**
added feature to autocomplete the arguments. argcomplete is required and to make argcomplete work, one have to "install" this
```
activate-global-python-argcomplete
```

or run

```bash
eval "$(register-python-argcomplete clustergit)"
```

### CODE REVIEW

**Comment by mnagel** [comment]
With my plain Ubuntu I get:

```
nailor@sting:~/code/clustergit$ clustergit            
Traceback (most recent call last):
  File "/home/nailor/bin/clustergit", line 9, in <module>
    from argcomplete import autocomplete
ImportError: No module named argcomplete
```

* This needs a graceful fallback. If I don't have argument completion, it needs to run without this functionality out of the box.

* I like the change to argparse from optparse.

* The API change of main breaks the test. That needs to be fixed.

```
nailor@sting:*de/clustergit/tests$ bash run-tests.sh batched
EEE
======================================================================
ERROR: tests.clustergit_test.TestClustergit.test_check_fresh_repo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/nailor/code/clustergit/tests/tests/clustergit_test.py", line 38, in test_check_fresh_repo
    clustergit.run('cd "%s"; mkdir mygit; cd mygit; git init' % (dirpath), clustergit.read_arguments(['-v']))
TypeError: read_arguments() takes no arguments (1 given)
-------------------- >> begin captured stdout << ---------------------
working in /tmp/tmp_zJKJa

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: tests.clustergit_test.TestClustergit.test_check_no_repo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/nailor/code/clustergit/tests/tests/clustergit_test.py", line 17, in test_check_no_repo
    clustergit.main([])
TypeError: main() takes no arguments (1 given)

======================================================================
ERROR: tests.clustergit_test.TestClustergit.test_excluded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/nailor/code/clustergit/tests/tests/clustergit_test.py", line 72, in test_excluded
    clustergit.read_arguments(['-v'])
TypeError: read_arguments() takes no arguments (1 given)
-------------------- >> begin captured stdout << ---------------------
working in /tmp/tmpt3XCMr

--------------------- >> end captured stdout << ----------------------

Name         Stmts   Miss Branch BrMiss  Cover   Missing
--------------------------------------------------------
clustergit     178    154     84     84     9%   12-14, 17-20, 23, 25, 36-163, 167-168, 171-176, 179-181, 188-313, 320-354
src              0      0      0      0   100%   
--------------------------------------------------------
TOTAL          178    154     84     84     9%   
----------------------------------------------------------------------
Ran 3 tests in 0.026s
```

**Comment by sedrubal** [comment]
* A *gracceful fallback* when missing `argparse` sounds good and possible. I'll implement this soon™
* I'm glad to hear that you like the change from `optparse` to `argparse`. I thought you have reasons for using `optparse`
* I'll look over the test errors soon™

**Comment by sedrubal** [comment]
Ah the test fails, because `argparse` reads the arguments directly and so the `main` and the `read_arguments` functions don't need / can't process the arguments as parameters. But the test has to provide the shell arguments as function parameters. One can remove the parameters in the test, but then the test has no function anymore... What do you think?

**Comment by mnagel** [comment]
`ArgumentParser.parse_args(args=None, namespace=None)` ( https://docs.python.org/2/library/argparse.html#the-parse-args-method ) should be able to process an array passed in as parameters instead of grabbing `sys.argv` itself -- basically just the same as the `optparse` code is doing right now.

That should "just work" and maintain compatibility with the test suite.

**Comment by sedrubal** [comment]
Mh thank you, I don't know why I reworked this... Maybe because I copy&pasted it from another project :) I should read more documentation...

Now the test suite is working again.

**Comment by sedrubal** [comment]
Is there still anything I should change?

**Comment by mnagel** [comment]
Code looks good now, but I cannot get it to function. I am on Ubuntu 14.04 and I run:

```
nailor@sting:~$ sudo apt-get install python-argcomplete
nailor@sting:~$ activate-global-python-argcomplete --user
Installing bash completion script /home/nailor/.bash_completion.d/python-argcomplete.sh
```

then I type in bash:
* `clustergit <TAB>` nothing happens
* `clustergit --<TAB>` nothing happens
* `clustergit --d<TAB>` nothing happens

How do I use it?

**Comment by sedrubal** [comment]
Mh yes unfortunately this does not work really good and I don't see any reason why...

Sometimes it workes after running `eval "$(register-python-argcomplete clustergit.py)"`

You can find more infos [here](https://github.com/kislyuk/argcomplete).

**Pull request merged**
