### PR TITLE
Execute command

### PR DESCRIPTION
**Pull request by sedrubal**
added option to execute a command in each repo.

### CODE REVIEW

**Comment by mnagel** [comment]
Hi there,

* I do not understand why do you remove coloring from command output. Wouldn't it be less cumbersome to run the command in a way that does not add color in the first place (like `--color=never`)?
* Adding `echo $?` after the command you run is cumbersome. We should use https://docs.python.org/2/library/commands.html#commands.getstatusoutput instead.
* Doing `cmd = run(cmd, options)` should be changed to `output = run(cmd, options)` to make it more clear that we get the output not some kind of reference to the command. Accessing `output[:-2]` was VERY confusing to me until I re-checked the additional `echo $?` above and noticed that it is buggy for exit codes with more than two decimal digits. It should absolutely be change to `getstatusoutput`
* Ideally, you could add a basic test to the test suite.

Besides that, it is a nice addition and I'd like to merge it when these issues are fixed.

Best Regards
Michael

**Comment by sedrubal** [comment]
Thank you for your reply and I'm glad you like it :)


* Removing color is only when running with `-n`. I thought you implemented this feature for scripts (that can't handle term colors) So every color produced by the executed command has to be removed
* Yes, `$?` is not how you want to do this I think :D https://docs.python.org/2/library/commands.html#commands.getstatusoutput sounds good. But then we also need something for python3
* Yes, I'll rename cmd to output... 
* `exit codes with more than two decimal digits` - I seem oops
* I didn't really realized the tests, sorry... Maybe I'll find something...

**Comment by sedrubal** [comment]
Thank you for merging both PRs :)

But I haven't fixed the problems above... maybe someone should do this some day...

**Comment by mnagel** [comment]
I added the usage of getstatusoutput, test are not mandatory and the discussion about colors was just for my understanding

**Comment by sedrubal** [comment]
ah ok I didn't see the `getstatusoutput`... ok, thank you

**Pull request merged**
